const fs = require('fs');
const path = require('path');

// Helper function to copy directories recursively
function copyRecursiveSync(src, dest) {
  const exists = fs.existsSync(src);
  const stats = exists && fs.statSync(src);
  const isDirectory = exists && stats.isDirectory();
  
  if (isDirectory) {
    if (!fs.existsSync(dest)) {
      fs.mkdirSync(dest, { recursive: true });
    }
    fs.readdirSync(src).forEach(childItemName => {
      copyRecursiveSync(
        path.join(src, childItemName),
        path.join(dest, childItemName)
      );
    });
  } else {
    fs.copyFileSync(src, dest);
  }
}

console.log('\n📦 Post-build: Preparing standalone folder for deployment...\n');

const projectRoot = path.resolve(__dirname, '..');
const standalonePath = path.join(projectRoot, '.next', 'standalone');

// Check if standalone folder exists
if (!fs.existsSync(standalonePath)) {
  console.error('❌ Error: .next/standalone folder not found. Make sure you ran "next build" first.');
  process.exit(1);
}

console.log(`📁 Standalone folder: ${standalonePath}\n`);

// Files to copy from project root to standalone folder (required for IIS)
const filesToCopy = [
  'web.config',      // IIS configuration (REQUIRED)
  'server.js'        // Node.js server entry (if custom, otherwise Next.js generates it)
];

let copiedCount = 0;
let skippedCount = 0;

// Copy each file
filesToCopy.forEach(file => {
  const sourcePath = path.join(projectRoot, file);
  const destPath = path.join(standalonePath, file);
  
  if (fs.existsSync(sourcePath)) {
    try {
      fs.copyFileSync(sourcePath, destPath);
      console.log(`✅ Copied: ${file}`);
      copiedCount++;
    } catch (error) {
      console.error(`❌ Error copying ${file}:`, error.message);
    }
  } else {
    // Check if file already exists in standalone (e.g., server.js generated by Next.js)
    if (fs.existsSync(destPath)) {
      console.log(`ℹ️  ${file} already exists in standalone (generated by Next.js)`);
    } else if (file === 'web.config') {
      // web.config is critical for IIS
      console.warn(`⚠️  Warning: ${file} not found! IIS deployment may fail without this file.`);
      skippedCount++;
    } else {
      console.warn(`⚠️  Warning: ${file} not found in project root, skipping...`);
      skippedCount++;
    }
  }
});

// Copy static folder from .next/static to .next/standalone/.next/static (CRITICAL for serving assets)
console.log('\n📁 Copying static assets folder...\n');
const staticSourcePath = path.join(projectRoot, '.next', 'static');
const staticDestPath = path.join(standalonePath, '.next', 'static');

if (fs.existsSync(staticSourcePath)) {
  try {
    // Remove existing static folder if it exists
    if (fs.existsSync(staticDestPath)) {
      fs.rmSync(staticDestPath, { recursive: true, force: true });
    }
    
    // Copy entire static folder recursively
    copyRecursiveSync(staticSourcePath, staticDestPath);
    console.log('✅ Copied: .next/static folder (CSS, JS bundles, fonts, etc.)');
  } catch (error) {
    console.error('❌ Error copying static folder:', error.message);
    console.error('⚠️  WARNING: Static assets may not load correctly without this folder!');
  }
} else {
  console.warn('⚠️  Warning: .next/static folder not found in build output!');
}

// Ensure .env.production exists with production API URL
const envProdPath = path.join(projectRoot, '.env.production');
const envProdDestPath = path.join(standalonePath, '.env.production');

// Production API URL (default)
const productionApiUrl = 'http://93.127.140.63:4000/api';

if (fs.existsSync(envProdPath)) {
  try {
    // Read existing .env.production
    const envContent = fs.readFileSync(envProdPath, 'utf8');
    
    // Check if NEXT_PUBLIC_API_URL exists and is not localhost
    if (envContent.includes('NEXT_PUBLIC_API_URL')) {
      // Check if it contains localhost (should not in production)
      if (envContent.includes('localhost')) {
        console.warn('⚠️  Warning: .env.production contains localhost! Updating to production URL...');
        // Replace localhost URL with production URL
        const updatedContent = envContent.replace(
          /NEXT_PUBLIC_API_URL=.*/g,
          `NEXT_PUBLIC_API_URL=${productionApiUrl}`
        );
        fs.writeFileSync(envProdDestPath, updatedContent);
        console.log('✅ Updated .env.production with production API URL');
      } else {
        // Copy as is
        fs.copyFileSync(envProdPath, envProdDestPath);
        console.log('✅ Copied: .env.production');
      }
    } else {
      // Add production API URL if not present
      const updatedContent = envContent + `\nNEXT_PUBLIC_API_URL=${productionApiUrl}\n`;
      fs.writeFileSync(envProdDestPath, updatedContent);
      console.log('✅ Added NEXT_PUBLIC_API_URL to .env.production');
    }
  } catch (error) {
    console.error('❌ Error processing .env.production:', error.message);
    // Create a new one with production URL
    try {
      fs.writeFileSync(envProdDestPath, `NEXT_PUBLIC_API_URL=${productionApiUrl}\n`);
      console.log('✅ Created .env.production with production API URL');
    } catch (createError) {
      console.error('❌ Error creating .env.production:', createError.message);
    }
  }
} else {
  // Create .env.production with production API URL
  try {
    fs.writeFileSync(envProdDestPath, `NEXT_PUBLIC_API_URL=${productionApiUrl}\n`);
    console.log('✅ Created .env.production with production API URL');
  } catch (error) {
    console.error('❌ Error creating .env.production:', error.message);
  }
}

// Verify essential files exist in standalone folder
console.log('\n🔍 Verifying essential files in standalone folder...\n');

const essentialFiles = [
  'server.js',
  'package.json',
  'web.config',
  '.next'
];

// Check if static folder exists in .next
const nextStaticPath = path.join(standalonePath, '.next', 'static');
if (fs.existsSync(nextStaticPath)) {
  console.log('✅ .next/static (folder) - Static assets (CSS, JS, fonts)');
} else {
  console.error('❌ .next/static - MISSING! Static assets will not load!');
  allFilesPresent = false;
}

let allFilesPresent = true;
essentialFiles.forEach(file => {
  const filePath = path.join(standalonePath, file);
  if (fs.existsSync(filePath)) {
    const stats = fs.statSync(filePath);
    const type = stats.isDirectory() ? 'folder' : 'file';
    console.log(`✅ ${file} (${type})`);
  } else {
    console.error(`❌ ${file} - MISSING!`);
    allFilesPresent = false;
  }
});

// Check node_modules
const nodeModulesPath = path.join(standalonePath, 'node_modules');
if (fs.existsSync(nodeModulesPath)) {
  console.log('✅ node_modules (folder)');
  
  // Verify Next.js is complete in node_modules
  const nextPath = path.join(nodeModulesPath, 'next');
  const nextWebpackPath = path.join(nextPath, 'dist', 'compiled', 'webpack');
  
  if (fs.existsSync(nextPath)) {
    if (fs.existsSync(nextWebpackPath)) {
      console.log('✅ node_modules/next/dist/compiled/webpack (Next.js webpack files present)');
    } else {
      console.warn('⚠️  WARNING: node_modules/next/dist/compiled/webpack is MISSING!');
      console.warn('   This will cause "Cannot find module webpack-lib" error!');
      console.warn('   Solution: Rebuild from scratch (delete .next and node_modules, then npm install && npm run build)');
      allFilesPresent = false;
    }
  } else {
    console.error('❌ node_modules/next - MISSING! Next.js is not installed!');
    allFilesPresent = false;
  }
} else {
  console.error('❌ node_modules - MISSING!');
  allFilesPresent = false;
}

// Summary
console.log('\n' + '='.repeat(60));
if (allFilesPresent) {
  console.log('✅ Post-build complete! Standalone folder is ready for deployment.');
} else {
  console.warn('⚠️  Post-build complete, but some files are missing. Please check above.');
}
console.log('='.repeat(60));
console.log(`\n📁 Standalone folder location:`);
console.log(`   ${standalonePath}\n`);
console.log('📋 Files copied:', copiedCount);
if (skippedCount > 0) {
  console.log('⚠️  Files skipped:', skippedCount);
}
console.log('\n🚀 Next steps:');
console.log('   1. Copy the entire .next/standalone folder to your IIS server');
console.log('   2. Ensure Node.js and iisnode are installed on IIS server');
console.log('   3. Point IIS website to the standalone folder\n');

